export const APPLICATION_STATUSES = [
  { value: "pending", label: "Pending" },
  { value: "verified", label: "Verified" },
  { value: "electricity_bill_name_mismatch", label: "Electricity Bill Name Mismatch" },
  { value: "electricity_bill_name_mismatch_completed_successfully", label: "Electricity Bill Name Mismatch – Completed Successfully" },
  { value: "electricity_bill_mismatch_ownership_transfer", label: "Electricity Bill Mismatch – Ownership Transfer" },
  { value: "ownership_transfer_completed_successfully", label: "Ownership Transfer – Completed Successfully" },
  { value: "consumer_login_submitted_to_govt_portal", label: "Consumer Login – Submitted to Govt Portal" },
  { value: "vendor_side_pending_for_bank_forward", label: "Vendor Side Pending for Bank Forward" },
  { value: "vendor_side_bank_forward", label: "Vendor Side – Bank Forward" },
  { value: "bank_reject", label: "Bank Reject" },
  { value: "vendor_side_re_bank_forward", label: "Vendor Side – Re-Bank Forward" },
  { value: "pending_for_loan_phase_1", label: "Pending for Loan – Phase 1" },
  { value: "loan_disbursed_successfully_phase_1", label: "Loan Disbursed Successfully – Phase 1" },
  { value: "vendor_side_invoice_generated", label: "Vendor Side – Invoice Generated" },
  { value: "e_way_bill_generated", label: "E-Way Bill Generated" },
  { value: "dcr_completed", label: "DCR Completed" },
  { value: "stock_forwarded_to_customer_home", label: "Forward the Stock to Customer Home" },
  { value: "technical_installation_pending", label: "Technical Side – Installation Pending" },
  { value: "technical_installation_half_work_done", label: "Technical Side – Installation Half Work Done" },
  { value: "technical_installation_completed", label: "Technical Side – Installation Completed" },
  { value: "vendor_installation_work_docx_uploaded_to_govt_portal", label: "Vendor Side – Installation Work DOCX Uploaded to Govt Portal" },
  { value: "load_announcement", label: "Load Announcement" },
  { value: "net_metering_completed_by_electricals_dept", label: "Net Metering Completed – by Electricals Dept" },
  { value: "solar_installation_completion_certificate", label: "Solar Installation Completion Certificate" },
  { value: "gps_photo_generated", label: "GPS Photo Generated" },
  { value: "docx_forwarded_to_bank_loan_phase_2", label: "Forward the DOCX to Bank Loan – Phase 2" },
  { value: "je_verification_pending", label: "JE Verification Pending" },
  { value: "je_verification_approved", label: "JE Verification – Approved" },
  { value: "pending_for_loan_disbursement_phase_2", label: "Pending for Loan Disbursement – Phase 2" },
  { value: "loan_disbursed_phase_2", label: "Loan Disbursed – Phase 2" },
  { value: "consumer_subsidy_pending", label: "Consumer – Subsidy Pending" },
  { value: "consumer_subsidy_disbursed", label: "Consumer – Subsidy Disbursed" },
  { value: "other", label: "Other" },
  // Legacy values remain selectable so existing records can still be managed.
  { value: "under_review", label: "Under Review" },
  { value: "submitted_to_govt", label: "Submitted to Govt" },
  { value: "approved", label: "Approved" },
  { value: "installed", label: "Installed" },
  { value: "rejected", label: "Rejected" },
  { value: "draft", label: "Draft" },
];

export const applicationStatusLabel = (value) =>
  APPLICATION_STATUSES.find((status) => status.value === value)?.label ||
  String(value || "").replace(/_/g, " ");
