import { useEffect,useState } from "react";
import { useNavigate,useParams } from "react-router-dom";
import { ArrowLeft,Clock,FileText,Loader2 } from "lucide-react";
import CareerDetailsModal from "../components/CareerDetailsModal";
import { fileUrl,getCareerDetail,updateCareerStatus } from "../services/api";

const STATUSES=[["new","New"],["shortlisted","Shortlisted"],["interview","Interview"],["hired","Hired"],["rejected","Rejected"]];
const dateTime=value=>value?new Date(value).toLocaleString("en-IN"):"—";
const title=value=>(value||"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function CareerDetail(){
 const {id}=useParams(),navigate=useNavigate();const [application,setApplication]=useState(null),[history,setHistory]=useState([]),[status,setStatus]=useState(""),[note,setNote]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[editing,setEditing]=useState(false);
 const load=async()=>{try{const res=await getCareerDetail(id);setApplication(res.data.application);setHistory(res.data.history||[]);setStatus(res.data.application.status);setError("");}catch(err){setError(err.message||"Could not load career application.");}finally{setLoading(false);}};
 useEffect(()=>{load();/* eslint-disable-line react-hooks/exhaustive-deps, react-hooks/set-state-in-effect */},[id]);
 const saveStatus=async()=>{if(!application||status===application.status)return;setSaving(true);setError("");try{await updateCareerStatus(id,status,note.trim());setNote("");await load();}catch(err){setError(err.message||"Could not update status.");}finally{setSaving(false);}};
 if(loading)return <div className="flex min-h-[40vh] items-center justify-center"><Loader2 className="animate-spin text-amber"/></div>;
 if(!application)return <p role="alert" className="rounded-xl border border-red-300 bg-red-50 p-6 text-sm text-red-700">{error||"Career application not found."}</p>;
 const name=`${application.first_name||""} ${application.last_name||""}`.trim();const timeline=history.length?history:[{id:"current",new_status:application.status,created_at:application.updated_at||application.created_at,changed_by_name:application.updated_by_name,note:"Older status changes were not recorded."}];
 const section=(heading,items)=><InfoSection key={heading} title={heading} items={items}/>;
 return <><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><button onClick={()=>navigate(-1)} className="mb-3 inline-flex items-center gap-2 rounded-full border border-navy/20 px-4 py-2 text-xs font-semibold text-navy"><ArrowLeft size={14}/>Back</button><p className="font-mono text-xs text-amber">Career Application #{application.id}</p><h2 className="mt-1 text-2xl font-extrabold text-navy">{name}</h2><p className="mt-1 text-sm text-muted">{application.phone} · {application.email}</p><p className="mt-1 text-xs text-muted">Created: {dateTime(application.created_at)} · Updated by {application.updated_by_name||"—"}: {dateTime(application.updated_at)}</p></div><button onClick={()=>setEditing(true)} className="rounded-full border border-navy/20 px-5 py-2.5 text-sm font-bold text-navy">Edit Details</button></div>
 {error&&<p role="alert" className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{editing&&<CareerDetailsModal application={application} onClose={()=>setEditing(false)} onSaved={async()=>{setEditing(false);await load();}}/>}
 <div className="grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2">{section("Personal Details",[["First Name",application.first_name],["Last Name",application.last_name],["Email",application.email],["Phone",application.phone],["Date of Birth",application.dob],["Gender",application.gender]])}{section("Address",[["Street Address",application.street_address],["City",application.city],["State",application.state],["Postal Code",application.postal_code],["Country",application.country]])}{section("Career Details",[["Job Role",application.jobrole],["Highest Qualification",title(application.qualification)]])}{section("About",[["Description",application.description]])}
 <div className="rounded-2xl border border-navy/10 bg-white p-5"><h3 className="text-sm font-bold text-navy">Resume / CV</h3>{application.cvUrl?<a href={fileUrl(application.cvUrl)} target="_blank" rel="noreferrer" className="mt-4 flex items-center gap-3 rounded-lg border border-navy/10 p-3 hover:border-amber"><FileText size={18} className="text-amber"/><span className="text-sm font-semibold text-navy">View uploaded CV</span></a>:<p className="mt-4 text-sm text-muted">No CV uploaded.</p>}</div>
 </div><div className="space-y-6"><div className="rounded-2xl border border-navy/10 bg-white p-5"><h3 className="text-sm font-bold text-navy">Update Status</h3><div className="mt-4 space-y-3"><select value={status} onChange={e=>setStatus(e.target.value)} className="w-full rounded-lg border border-navy/15 bg-white px-3.5 py-2.5 text-sm">{STATUSES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Note (optional)" rows={3} className="w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm"/><button onClick={saveStatus} disabled={saving||status===application.status} className="w-full rounded-full bg-amber px-5 py-2.5 text-sm font-bold text-navy disabled:opacity-60">{saving?"Saving...":"Save Status"}</button></div></div>
 <div className="rounded-2xl border border-navy/10 bg-white p-5"><h3 className="flex items-center gap-2 text-sm font-bold text-navy"><Clock size={16} className="text-amber"/>Status Timeline</h3><div className="mt-4 space-y-3">{timeline.map(entry=><div key={entry.id} className="border-l-2 border-amber/40 pl-3"><p className="text-xs font-bold text-navy">{title(entry.new_status)}</p><p className="text-xs text-muted">{dateTime(entry.created_at)}</p><p className="text-xs text-muted">by {entry.changed_by_name||"Applicant"}</p>{entry.note&&<p className="mt-1 text-xs italic text-muted">{entry.note}</p>}</div>)}</div></div></div></div></>;
}
function InfoSection({title,items}){const visible=items.filter(([,v])=>v!==null&&v!==undefined&&v!=="");return <div className="rounded-2xl border border-navy/10 bg-white p-5"><h3 className="text-sm font-bold text-navy">{title}</h3>{visible.length?<div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2">{visible.map(([label,value])=><div key={label}><p className="text-xs font-semibold text-muted">{label}</p><p className="mt-0.5 whitespace-pre-wrap text-sm font-medium text-navy">{String(value)}</p></div>)}</div>:<p className="mt-4 text-sm text-muted">No data.</p>}</div>;}
