import {useEffect,useState} from "react";
import {useNavigate,useParams} from "react-router-dom";
import {ArrowLeft,Clock,Download,Loader2} from "lucide-react";
import ContactDetailsModal from "../components/ContactDetailsModal";
import {downloadSubmissionPdf,getContactDetail,updateContactStatus} from "../services/api";
const STATUSES=[["new","New"],["contacted","Contacted"],["converted","Converted"],["closed","Closed"]];
const dateTime=v=>v?new Date(v).toLocaleString("en-IN"):"—";
const title=v=>(v||"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function ContactDetail(){
 const {id}=useParams(),navigate=useNavigate();const [contact,setContact]=useState(null),[history,setHistory]=useState([]),[status,setStatus]=useState(""),[note,setNote]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[editing,setEditing]=useState(false);
 const load=async()=>{try{const r=await getContactDetail(id);setContact(r.data.contact);setHistory(r.data.history||[]);setStatus(r.data.contact.status);setError("");}catch(e){setError(e.message||"Could not load contact enquiry.");}finally{setLoading(false);}};
 useEffect(()=>{load();/* eslint-disable-line react-hooks/exhaustive-deps, react-hooks/set-state-in-effect */},[id]);
 const saveStatus=async()=>{if(!contact||status===contact.status)return;setSaving(true);setError("");try{await updateContactStatus(id,status,note.trim());setNote("");await load();}catch(e){setError(e.message||"Could not update status.");}finally{setSaving(false);}};
 if(loading)return <div className="flex min-h-[40vh] items-center justify-center"><Loader2 className="animate-spin text-amber"/></div>;
 if(!contact)return <p role="alert" className="rounded-xl border border-red-300 bg-red-50 p-6 text-sm text-red-700">{error||"Contact enquiry not found."}</p>;
 const timeline=history.length?history:[{id:"current",new_status:contact.status,created_at:contact.updated_at||contact.created_at,changed_by_name:contact.updated_by_name,note:"Older status changes were not recorded."}];
 return <><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><button onClick={()=>navigate(-1)} className="mb-3 inline-flex items-center gap-2 rounded-full border border-navy/20 px-4 py-2 text-xs font-semibold text-navy"><ArrowLeft size={14}/>Back</button><p className="font-mono text-xs text-amber">Contact Enquiry #{contact.id}</p><h2 className="mt-1 text-2xl font-extrabold text-navy">{contact.name}</h2><p className="mt-1 text-sm text-muted">{contact.phone} · {contact.email||"No email"}</p><p className="mt-1 text-xs text-muted">Created: {dateTime(contact.created_at)} · Updated by {contact.updated_by_name||"—"}: {dateTime(contact.updated_at)}</p></div><div className="flex gap-2"><button onClick={()=>setEditing(true)} className="rounded-full border border-navy/20 px-5 py-2.5 text-sm font-bold text-navy">Edit Details</button><button onClick={()=>downloadSubmissionPdf("contacts",contact.id)} className="flex items-center gap-2 rounded-full bg-amber px-5 py-2.5 text-sm font-bold text-navy"><Download size={16}/>Download PDF</button></div></div>
 {error&&<p role="alert" className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{editing&&<ContactDetailsModal contact={contact} onClose={()=>setEditing(false)} onSaved={async()=>{setEditing(false);await load();}}/>}
 <div className="grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><InfoSection title="Contact Details" items={[["Name",contact.name],["Phone",contact.phone],["Email",contact.email],["City",contact.city],["System Size",contact.system_size],["Message",contact.message],["Created",dateTime(contact.created_at)]]}/></div><div className="space-y-6"><div className="rounded-2xl border border-navy/10 bg-white p-5"><h3 className="text-sm font-bold text-navy">Update Status</h3><div className="mt-4 space-y-3"><select value={status} onChange={e=>setStatus(e.target.value)} className="w-full rounded-lg border border-navy/15 bg-white px-3.5 py-2.5 text-sm">{STATUSES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Note (optional)" rows={3} className="w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm"/><button onClick={saveStatus} disabled={saving||status===contact.status} className="w-full rounded-full bg-amber px-5 py-2.5 text-sm font-bold text-navy disabled:opacity-60">{saving?"Saving...":"Save Status"}</button></div></div><div className="rounded-2xl border border-navy/10 bg-white p-5"><h3 className="flex items-center gap-2 text-sm font-bold text-navy"><Clock size={16} className="text-amber"/>Status Timeline</h3><div className="mt-4 space-y-3">{timeline.map(e=><div key={e.id} className="border-l-2 border-amber/40 pl-3"><p className="text-xs font-bold text-navy">{title(e.new_status)}</p><p className="text-xs text-muted">{dateTime(e.created_at)}</p><p className="text-xs text-muted">by {e.changed_by_name||"Customer"}</p>{e.note&&<p className="mt-1 text-xs italic text-muted">{e.note}</p>}</div>)}</div></div></div></div></>;
}
function InfoSection({title,items}){const visible=items.filter(([,v])=>v!==null&&v!==undefined&&v!=="");return <div className="rounded-2xl border border-navy/10 bg-white p-5"><h3 className="text-sm font-bold text-navy">{title}</h3><div className="mt-4 grid gap-4 sm:grid-cols-2">{visible.map(([label,value])=><div key={label}><p className="text-xs font-semibold text-muted">{label}</p><p className="mt-0.5 whitespace-pre-wrap text-sm font-medium text-navy">{String(value)}</p></div>)}</div></div>;}
