import { useEffect, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { ArrowLeft, Clock, Download, FileText, Loader2 } from "lucide-react";
import JoinUsDetailsModal from "../components/JoinUsDetailsModal";
import { downloadJoinUsLOA, downloadSubmissionPdf, fileUrl, getJoinUsDetail, updateJoinUsStatus } from "../services/api";

const STATUSES = [["rehired","Re-Hired"],["reviewed","Reviewed"],["shortlisted","Shortlisted"],["onboarded","Onboarded"],["terminated","Terminated"],["resigned","Resigned"],["on_leave","On Leave"],["salary_success","Salary Success"],["rejected","Rejected"]];
const dateTime = (value) => value ? new Date(value).toLocaleString("en-IN") : "—";
const title = (value = "") => value.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function JoinUsDetail() {
  const { id } = useParams(); const navigate = useNavigate(); const [searchParams] = useSearchParams(); const editRequested = searchParams.get("edit") === "1";
  const [submission,setSubmission]=useState(null),[history,setHistory]=useState([]),[status,setStatus]=useState(""),[note,setNote]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[editing,setEditing]=useState(false),[loaNotice,setLoaNotice]=useState("");
  const load=async()=>{try{const res=await getJoinUsDetail(id);setSubmission(res.data.submission);setHistory(res.data.history||[]);setStatus(res.data.submission.status);setError("");}catch(err){setError(err.message||"Could not load Join Us details.");}finally{setLoading(false);}};
  useEffect(()=>{load(); /* eslint-disable-line react-hooks/exhaustive-deps, react-hooks/set-state-in-effect */},[id]);
  const saveStatus=async()=>{if(!submission||status===submission.status)return;setSaving(true);setError("");try{await updateJoinUsStatus(id,status,note.trim());setNote("");await load();}catch(err){setError(err.message||"Could not update status.");}finally{setSaving(false);}};
  const handleDownloadLOA=async()=>{const required=["appointment_designation","joining_date","gross_salary","net_salary","annual_ctc"];if(required.some(key=>!String(submission?.[key]||"").trim())){setLoaNotice("Fill Appointment Designation, Date of Joining, Monthly Gross Salary, Monthly Net Salary and Annual CTC, then save the details to create the LOA.");setEditing(true);return;}setError("");try{await downloadJoinUsLOA(id);}catch(err){setError(err.message||"Could not download the appointment letter.");}};
  if(loading)return <div className="flex min-h-[40vh] items-center justify-center"><Loader2 className="animate-spin text-amber"/></div>;
  if(!submission)return <div role="alert" className="rounded-xl border border-red-300 bg-red-50 p-6 text-sm text-red-700">{error||"Join Us submission not found."}</div>;
  const fullName=`${submission.first_name||""} ${submission.last_name||""}`.trim();
  const docs=Object.entries(submission.documentUrls||{});
  const timeline=history.length?history:[{id:"current",new_status:submission.status,created_at:submission.updated_at||submission.created_at,changed_by_name:submission.updated_by_name,note:"Older status changes were not recorded."}];
  const section=(heading,items)=><InfoSection key={heading} title={heading} items={items}/>;
  return <>
    <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><button onClick={()=>navigate(-1)} className="mb-3 inline-flex items-center gap-2 rounded-full border border-navy/20 px-4 py-2 text-xs font-semibold text-navy"><ArrowLeft size={14}/>Back</button><p className="font-mono text-xs text-amber">Join Us #{submission.id}</p><h2 className="mt-1 text-2xl font-extrabold text-navy">{fullName}</h2><p className="mt-1 text-sm text-muted">{submission.phone} · {submission.email}</p><p className="mt-1 text-xs text-muted">Created: {dateTime(submission.created_at)} · Updated by {submission.updated_by_name||"—"}: {dateTime(submission.updated_at)}</p></div><div className="flex gap-2"><button onClick={()=>setEditing(true)} className="rounded-full border border-navy/20 px-5 py-2.5 text-sm font-bold text-navy">Edit Details</button><button onClick={()=>downloadSubmissionPdf("join-us",submission.id)} className="flex items-center gap-2 rounded-full bg-amber px-5 py-2.5 text-sm font-bold text-navy"><Download size={16}/>Download Details PDF</button><button onClick={handleDownloadLOA} className="flex items-center gap-2 rounded-full bg-amber px-5 py-2.5 text-sm font-bold text-navy"><Download size={16}/>Download LOA</button></div></div>
    {error&&<p role="alert" className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {(editing||editRequested)&&<JoinUsDetailsModal submission={submission} loaNotice={loaNotice} onClose={()=>{setEditing(false);setLoaNotice("");if(editRequested)navigate(`/admin/join-us/${id}`,{replace:true});}} onSaved={async()=>{setEditing(false);setLoaNotice("");if(editRequested)navigate(`/admin/join-us/${id}`,{replace:true});await load();}}/>}
    <div className="grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2">
      {section("Personal Details",[["First Name",submission.first_name],["Last Name",submission.last_name],["Email",submission.email],["Phone",submission.phone],["Date of Birth",submission.dob],["Gender",submission.gender],["Father's Name",submission.father_name],["Mother's Name",submission.mother_name],["Blood Group",submission.blood_group],["Guardian Name",submission.guardian_name],["Guardian Mobile Number",submission.guardian_mobile],["Marital Status",submission.marital_status]])}
      {section("Current Address",[["Street Address",submission.street_address],["City",submission.city],["District",submission.district],["State",submission.state],["Location / Posting Preference",submission.location],["Postal Code",submission.postal_code],["Country",submission.country]])}
      {section("Permanent Address",[["Same as Current",submission.same_as_above?"Yes":"No"],["Address",submission.permanent_address],["City",submission.permanent_city],["State",submission.permanent_state],["Postal Code",submission.permanent_postal_code]])}
      {section("Identity Details",[["Aadhaar Number",submission.aadhaar_number],["PAN Number",submission.pan_number]])}
      {section("Education & Experience",[["Qualification",title(submission.qualification)],["Institution",submission.institution_name],["Year of Passing",submission.year_of_passing],["Experience",title(submission.experience)],["Company",submission.company_name],["Current / Last Designation",submission.designation]])}{section("Appointment Details",[["Appointment Designation",submission.appointment_designation],["Date of Joining",submission.joining_date],["Place of Posting",submission.office_location],["Monthly Gross Salary",submission.gross_salary],["Monthly Net Salary",submission.net_salary],["Allowance",submission.allowance],["Annual CTC",submission.annual_ctc],["Probation Period",submission.probation_period],["Notice Period",submission.notice_period],["LOA Reference Number",submission.reference_number]])}
      {section("Bank Details",[["Bank Name",submission.bank_name],["Account Number",submission.account_number],["IFSC Code",submission.ifsc_code]])}
      {section("About",[["Description",submission.description]])}
      <div className="rounded-2xl border border-navy/10 bg-white p-5"><h3 className="text-sm font-bold text-navy">Uploaded Documents</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">{docs.map(([label,url])=><a key={label} href={fileUrl(url)} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-lg border border-navy/10 p-3 hover:border-amber"><FileText size={18} className="text-amber"/><span className="text-sm font-semibold text-navy">{label}</span></a>)}{!docs.length&&<p className="text-sm text-muted">No documents uploaded.</p>}</div></div>
    </div><div className="space-y-6"><div className="rounded-2xl border border-navy/10 bg-white p-5"><h3 className="text-sm font-bold text-navy">Update Status</h3><div className="mt-4 space-y-3"><select value={status} onChange={e=>setStatus(e.target.value)} className="w-full rounded-lg border border-navy/15 bg-white px-3.5 py-2.5 text-sm">{status==="new"&&<option value="new">New (current)</option>}{STATUSES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Note (optional)" rows={3} className="w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm"/><button onClick={saveStatus} disabled={saving||status===submission.status} className="w-full rounded-full bg-amber px-5 py-2.5 text-sm font-bold text-navy disabled:opacity-60">{saving?"Saving...":"Save Status"}</button></div></div>
      <div className="rounded-2xl border border-navy/10 bg-white p-5"><h3 className="flex items-center gap-2 text-sm font-bold text-navy"><Clock size={16} className="text-amber"/>Status Timeline</h3><div className="mt-4 space-y-3">{timeline.map(entry=><div key={entry.id} className="border-l-2 border-amber/40 pl-3"><p className="text-xs font-bold text-navy">{title(entry.new_status)}</p><p className="text-xs text-muted">{dateTime(entry.created_at)}</p><p className="text-xs text-muted">by {entry.changed_by_name||"Applicant"}</p>{entry.note&&<p className="mt-1 text-xs italic text-muted">{entry.note}</p>}</div>)}</div></div>
    </div></div>
  </>;
}
function InfoSection({title,items}){const visible=items.filter(([,v])=>v!==null&&v!==undefined&&v!=="");return <div className="rounded-2xl border border-navy/10 bg-white p-5"><h3 className="text-sm font-bold text-navy">{title}</h3>{visible.length?<div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2">{visible.map(([label,value])=><div key={label}><p className="text-xs font-semibold text-muted">{label}</p><p className="mt-0.5 whitespace-pre-wrap text-sm font-medium text-navy">{String(value)}</p></div>)}</div>:<p className="mt-4 text-sm text-muted">No data.</p>}</div>;}
