import { useState } from "react";
import { fileUrl, updateCareer, uploadFilesToS3 } from "../services/api";

const FIELDS=[["firstName","First Name"],["lastName","Last Name"],["email","Email","email"],["phone","Phone"],["dob","Date of Birth"],["gender","Gender","gender"],["streetAddress","Street Address"],["city","City"],["district","District"],["state","State"],["postalCode","Postal Code"],["country","Country"],["jobrole","Job Role"],["location","Location","location"],["qualification","Qualification"],["description","Description","textarea"]];
export default function CareerDetailsModal({application,onClose,onSaved}){
 const [form,setForm]=useState(()=>Object.fromEntries(FIELDS.map(([key])=>[key,application[key]||""]))),[cv,setCv]=useState(null),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const save=async e=>{e.preventDefault();setSaving(true);setError("");try{const files=await uploadFilesToS3("careers",cv?{cv}:{});await updateCareer(application.id,{...form,files});await onSaved();}catch(err){setError(err.message||"Could not update career application.");}finally{setSaving(false);}};
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-navy/60 p-4"><form onSubmit={save} className="mx-auto my-5 max-w-4xl rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><div><h3 className="text-xl font-extrabold text-navy">Edit Career Application</h3><p className="mt-1 text-xs text-muted">Application #{application.id}</p></div><button type="button" onClick={onClose} className="text-sm font-bold text-muted">Close</button></div>
 {error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-2">{FIELDS.map(([key,label,type])=><label key={key} className={`text-xs font-semibold text-navy/70 ${type==="textarea"?"sm:col-span-2":""}`}>{label}{type==="textarea"?<textarea rows={3} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded-lg border border-navy/15 px-3 py-2 text-sm"/>:type==="gender"||type==="location"?<select required={type==="location"} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded-lg border border-navy/15 px-3 py-2 text-sm">{type==="location"&&<option value="" disabled>Select location</option>}{(type==="gender"?["Male","Female","Other"]:["Odisha","West Bengal"]).map(v=><option key={v}>{v}</option>)}</select>:<input type={type||"text"} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded-lg border border-navy/15 px-3 py-2 text-sm"/>}</label>)}</div>
 <div className="mt-5 border-t border-navy/10 pt-4"><p className="text-sm font-bold text-navy">Resume / CV</p>{application.cvUrl?<a href={fileUrl(application.cvUrl)} target="_blank" rel="noreferrer" className="mt-1 inline-block text-xs font-semibold text-amber">View current CV</a>:<p className="mt-1 text-xs text-muted">No CV uploaded</p>}<input type="file" accept=".pdf,.doc,.docx" onChange={e=>setCv(e.target.files?.[0]||null)} className="mt-2 block w-full text-xs"/></div>
 <div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-full border border-navy/20 px-5 py-2.5 text-sm font-bold text-navy">Cancel</button><button disabled={saving} className="rounded-full bg-amber px-5 py-2.5 text-sm font-bold text-navy disabled:opacity-60">{saving?"Saving...":"Save Changes"}</button></div></form></div>;
}
