import { useState } from "react";
import { updateContact } from "../services/api";

const FIELDS=[["name","Name"],["phone","Phone"],["email","Email","email"],["city","City"],["systemSize","System Size"],["message","Message","textarea"]];
export default function ContactDetailsModal({contact,onClose,onSaved}){
 const [form,setForm]=useState(()=>Object.fromEntries(FIELDS.map(([key])=>[key,contact[key]??(key==="systemSize"?contact.system_size:"")]))),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const save=async e=>{e.preventDefault();setSaving(true);setError("");try{await updateContact(contact.id,form);await onSaved();}catch(err){setError(err.message||"Could not update contact enquiry.");}finally{setSaving(false);}};
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-navy/60 p-4"><form onSubmit={save} className="mx-auto my-8 max-w-2xl rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><div><h3 className="text-xl font-extrabold text-navy">Edit Contact Enquiry</h3><p className="mt-1 text-xs text-muted">Enquiry #{contact.id}</p></div><button type="button" onClick={onClose} className="text-sm font-bold text-muted">Close</button></div>{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-2">{FIELDS.map(([key,label,type])=><label key={key} className={`text-xs font-semibold text-navy/70 ${type==="textarea"?"sm:col-span-2":""}`}>{label}{type==="textarea"?<textarea rows={4} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded-lg border border-navy/15 px-3 py-2 text-sm"/>:<input type={type||"text"} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded-lg border border-navy/15 px-3 py-2 text-sm"/>}</label>)}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-full border border-navy/20 px-5 py-2.5 text-sm font-bold text-navy">Cancel</button><button disabled={saving} className="rounded-full bg-amber px-5 py-2.5 text-sm font-bold text-navy disabled:opacity-60">{saving?"Saving...":"Save Changes"}</button></div></form></div>;
}
